version: "3.7"

services:
  # mongo-db:
  #   image: mongo
  #   restart: always
  #   environment:
  #     MONGO_INITDB_ROOT_USERNAME: samir-ze-delivery
  #     MONGO_INITDB_ROOT_PASSWORD: 
  #   volumes:
  #     - mongo-db:/data/db


  # mongo-express:
  #   image: mongo-express
  #   restart: always
  #   ports:
  #     - 8081:8081
  #   links: 
  #     - db
  #   environment:
  #     ME_CONFIG_MONGODB_ADMINUSERNAME: samir-ze-delivery
  #     ME_CONFIG_MONGODB_ADMINPASSWORD: 
  #     # ME_CONFIG_MONGODB_URL: 
  #   networks:
  #     - mongo-compose

  app:
    build: .
    container_name: ze-delivery-backend
    restart: always
    ports: 
      - 3333:3333
      - 9229:9229
    volumes:
      - .:/usr/app
    # links: 
    #   - mongo-db
    # depends_on:
    #   - mongo-db
  
# volumes:
#   mongo-db: {}
